site_name: SQLumAI Docs
theme:
  name: material
nav:
  - Home: index.md
  - Architecture: architecture.md
  - MVPs: mvp.md
  - Enforcement: ENFORCEMENT.md
  - How-To: howto-reports.md
  - Integration: howto-integration.md
  - Examples: examples.md
  - High Availability: ha.md
  - QA Checklist: qa-checklist.md
  - Test Strategy: test-strategy.md
  - Metrics Dashboard: metrics-dashboard.md
  - Benchmarks: benchmarks.md
  - Dry-Run JSON: dryrun-json.md
  - Dry-Run Chart: dryrun-chart.md
  - LLM Providers: llm-providers.md
  - Insights: insights.md
  - Release: release.md
docs_dir: docs
